export const articlesData = [
  {
    id: 1,
    title: '5 Tips Merawat Kucing Peliharaan Anda di Musim Panas',
    slug: '5-tips-merawat-kucing-di-musim-panas',
    category: 'Pet Care',
    excerpt: 'Musim panas memerlukan perhatian khusus untuk kesehatan kucing Anda. Pelajari cara menjaga kucing tetap nyaman dan sehat...',
    content: 'Kucing lebih rentan terhadap panas dibanding anjing karena mereka tidak memiliki kelenjar keringat yang efektif. Berikut adalah tips-tips penting untuk menjaga kucing Anda tetap sehat dan nyaman selama musim panas:',
    longContent: 'Pertama, pastikan selalu ada air minum segar yang tersedia di berbagai tempat di rumah Anda. Kucing cenderung minum lebih sedikit dari yang dibutuhkan, jadi dengan menyediakan air di beberapa lokasi, Anda dapat mendorong mereka untuk minum lebih banyak. Kedua, berikan ruang yang sejuk dan teduh untuk kucing beristirahat, jauh dari sinar matahari langsung. Ketiga, hindari grooming yang terlalu sering karena bulu mereka berfungsi sebagai isolasi termal. Keempat, perhatikan tanda-tanda heatstroke seperti muntah, diare, atau kebingungan. Dan terakhir, hindari membawa kucing keluar saat suhu puncak pada siang hari.',
    date: '2024-11-15',
    image: '/cute-cat-in-cool-environment-during-summer.jpg',
  },
  {
    id: 2,
    title: 'Grooming Anjing: Panduan Lengkap Perawatan Bulu yang Sempurna',
    slug: 'grooming-anjing-panduan-lengkap',
    category: 'Grooming Tips',
    excerpt: 'Grooming bukan hanya tentang keindahan, tetapi juga kesehatan. Cari tahu teknik dan produk yang tepat untuk anjing Anda...',
    content: 'Grooming yang tepat adalah bagian penting dari perawatan kesehatan anjing Anda. Grooming yang baik tidak hanya membuat anjing Anda terlihat cantik, tetapi juga mencegah masalah kesehatan seperti infeksi kulit, telinga bermasalah, dan kuku yang terlalu panjang.',
    longContent: 'Sebelum memulai grooming, siapkan semua peralatan yang diperlukan seperti sikat, gunting, dan produk pembersih khusus anjing. Mulai dengan menyikat bulu anjing secara menyeluruh untuk menghilangkan kusut dan rambut mati. Setelah itu, lanjutkan dengan memandikan anjing menggunakan air hangat dan shampoo khusus anjing. Jangan lupa untuk membersihkan telinga, memotong kuku, dan menyikat gigi secara teratur. Frekuensi grooming tergantung pada jenis bulu anjing Anda. Anjing dengan bulu panjang memerlukan grooming setiap 4-8 minggu, sementara anjing dengan bulu pendek dapat digrooming setiap 8-12 minggu.',
    date: '2024-11-12',
    image: '/professional-dog-grooming-with-happy-dog.jpg',
  },
  {
    id: 3,
    title: 'Vaksinasi Anjing: Jadwal Penting dan Jenis-Jenis Vaksin',
    slug: 'vaksinasi-anjing-jadwal-dan-jenis',
    category: 'Pet Health',
    excerpt: 'Vaksinasi adalah bagian krusial dari perawatan kesehatan anjing. Ketahui jadwal vaksinasi yang direkomendasikan dan pentingnya...',
    content: 'Vaksinasi memainkan peran penting dalam melindungi anjing Anda dari penyakit-penyakit berbahaya. Vaksin yang tepat pada waktu yang tepat dapat menyelamatkan nyawa anjing Anda dan mencegah penyebaran penyakit ke anjing lain.',
    longContent: 'Anjing anak-anak biasanya mulai divaksinasi pada usia 6-8 minggu. Vaksin inti yang direkomendasikan termasuk vaksin rabies dan parvovirus. Anjing memerlukan seri vaksin awal yang biasanya diberikan setiap 3-4 minggu hingga usia 16 minggu, diikuti dengan booster tahunan. Vaksin non-inti seperti vaksin leptospirosis, bordetella, dan lyme dapat diberikan tergantung pada gaya hidup dan risiko anjing Anda. Konsultasikan dengan dokter hewan Anda untuk menentukan jadwal vaksinasi yang paling sesuai untuk anjing Anda.',
    date: '2024-11-08',
    image: '/veterinarian-vaccinating-a-healthy-dog.jpg',
  },
  {
    id: 4,
    title: 'Cara Mengenali Tanda-Tanda Stress pada Hewan Peliharaan',
    slug: 'tanda-tanda-stress-hewan-peliharaan',
    category: 'Pet Health',
    excerpt: 'Hewan peliharaan juga bisa mengalami stress. Pelajari gejala-gejala yang perlu diperhatikan dan cara membantu mereka...',
    content: 'Stress pada hewan peliharaan dapat disebabkan oleh berbagai faktor seperti perubahan lingkungan, kehadiran hewan baru, atau perubahan rutinitas. Mengenali tanda-tanda stress dapat membantu Anda mengambil tindakan lebih awal.',
    longContent: 'Tanda-tanda stress pada anjing termasuk berlebihan menggonggong, menggigit, atau perilaku destruktif lainnya. Anjing yang stress mungkin juga menunjukkan perubahan pola makan atau tidur, atau menjadi pendiam dan menarik diri. Untuk kucing, stress dapat ditunjukkan melalui perubahan kebiasaan toilet, grooming yang berlebihan, atau perilaku agresif. Jika Anda melihat tanda-tanda ini, coba identifikasi sumber stress dan hilangkan jika mungkin. Berikan lingkungan yang tenang, mainan untuk dimainkan, dan waktu kualitas bersama hewan peliharaan Anda. Jika stress berlanjut, konsultasikan dengan dokter hewan Anda.',
    date: '2024-11-05',
    image: '/relaxed-and-happy-pets-in-calm-environment.jpg',
  },
  {
    id: 5,
    title: 'Nutrisi Optimal untuk Hewan Peliharaan: Panduan Lengkap',
    slug: 'nutrisi-optimal-hewan-peliharaan',
    category: 'Pet Care',
    excerpt: 'Nutrisi yang tepat adalah fondasi kesehatan hewan peliharaan. Ketahui kebutuhan nutrisi dan pilihan makanan terbaik...',
    content: 'Nutrisi yang seimbang sangat penting untuk kesehatan dan longevity hewan peliharaan Anda. Kebutuhan nutrisi berbeda untuk setiap spesies dan usia hewan peliharaan.',
    longContent: 'Anjing membutuhkan protein berkualitas, lemak, karbohidrat, vitamin, dan mineral dalam jumlah yang tepat. Kualitas makanan komersial bervariasi, jadi pilihlah makanan dengan bahan-bahan berkualitas tinggi dan tanpa pengawet berbahaya. Untuk kucing, mereka adalah karnivora obligat yang membutuhkan protein tinggi dan taurin. Konsultasikan dengan dokter hewan Anda untuk menentukan pilihan makanan terbaik untuk hewan peliharaan Anda berdasarkan usia, kesehatan, dan kebutuhan khusus mereka.',
    date: '2024-11-02',
    image: '/healthy-nutritious-pet-food-and-fresh-ingredients.jpg',
  },
  {
    id: 6,
    title: 'Latihan dan Aktivitas untuk Hewan Peliharaan yang Sehat',
    slug: 'latihan-aktivitas-hewan-sehat',
    category: 'Pet Care',
    excerpt: 'Latihan rutin sangat penting untuk kesehatan fisik dan mental hewan peliharaan. Temukan jenis aktivitas yang tepat...',
    content: 'Hewan peliharaan yang aktif adalah hewan peliharaan yang sehat dan bahagia. Latihan membantu menjaga berat badan, memperkuat otot, dan meningkatkan kesehatan mental.',
    longContent: 'Anjing membutuhkan latihan harian yang bervariasi tergantung pada usia, ukuran, dan tingkat energi mereka. Anjing muda dan energik mungkin memerlukan hingga 2 jam latihan sehari, sementara anjing tua atau berukuran kecil mungkin hanya memerlukan 30 menit. Kucing juga memerlukan aktivitas untuk tetap sehat, meskipun mereka cenderung lebih santai. Mainan interaktif, laser pointers, dan papan main dapat membantu kucing Anda tetap aktif. Latihan tidak hanya baik untuk kesehatan fisik tetapi juga untuk kesehatan mental dan perilaku hewan peliharaan Anda.',
    date: '2024-10-30',
    image: '/active-dog-playing-and-exercising-in-park.jpg',
  },
  {
    id: 7,
    title: 'Perawatan Gigi Hewan Peliharaan: Tips Menjaga Gigi Tetap Sehat',
    slug: 'perawatan-gigi-hewan-peliharaan',
    category: 'Pet Health',
    excerpt: 'Kesehatan gigi penting untuk kesehatan keseluruhan. Pelajari cara merawat gigi hewan peliharaan Anda dengan benar...',
    content: 'Penyakit gigi adalah masalah kesehatan yang umum pada hewan peliharaan dan dapat menyebabkan masalah kesehatan yang lebih serius. Perawatan gigi yang tepat dapat mencegah masalah ini.',
    longContent: 'Menyikat gigi hewan peliharaan secara teratur adalah cara terbaik untuk menjaga kesehatan gigi mereka. Gunakan sikat gigi dan pasta khusus hewan peliharaan, jangan gunakan pasta gigi manusia. Sikat gigi setidaknya 3-4 kali per minggu, atau setiap hari jika memungkinkan. Selain itu, makanan keras atau mainan yang dapat dimainkan dapat membantu membersihkan gigi secara alami. Kunjungi dokter gigi hewan secara teratur untuk pembersihan profesional dan pemeriksaan kesehatan gigi.',
    date: '2024-10-28',
    image: '/veterinarian-checking-pet-teeth-dental-health.jpg',
  },
  {
    id: 8,
    title: 'Memilih Hewan Peliharaan yang Tepat untuk Gaya Hidup Anda',
    slug: 'memilih-hewan-peliharaan-yang-tepat',
    category: 'Pet Care',
    excerpt: 'Memilih hewan peliharaan yang tepat sangat penting untuk kesuksesan jangka panjang. Pelajari apa yang perlu dipertimbangkan...',
    content: 'Memiliki hewan peliharaan adalah tanggung jawab besar yang memerlukan pertimbangan matang. Sebelum membawa hewan peliharaan ke rumah, pastikan Anda siap untuk komitmen jangka panjang.',
    longContent: 'Pertimbangkan ruang yang Anda miliki, waktu yang dapat Anda curahkan, anggaran yang tersedia, dan alergi keluarga. Anjing memerlukan lebih banyak perhatian dan aktivitas dibanding kucing. Beberapa ras anjing dapat hidup hingga 15 tahun atau lebih. Jika Anda sering bekerja atau bepergian, mungkin kucing atau hewan peliharaan dengan kebutuhan perawatan yang lebih rendah lebih cocok. Kunjungi panti asuhan lokal untuk melihat hewan-hewan yang membutuhkan rumah. Dengan memilih hewan peliharaan yang tepat, Anda akan menciptakan hubungan yang bermakna dan memuaskan.',
    date: '2024-10-25',
    image: '/happy-family-with-pet-dog-and-cat.jpg',
  },
]
